from pydantic import BaseModel, Field


class StrategyRequest(BaseModel):
    product: str = Field(
        ...,
        min_length=2,
        description="Product or service being marketed"
    )

    persona: str = Field(
        ...,
        min_length=2,
        description="Customer persona generated by Customer Intelligence"
    )

    marketing_goal: str = Field(
        ...,
        min_length=2,
        description="Marketing objective"
    )

    platform: str = Field(
        ...,
        min_length=2,
        description="Marketing platform"
    )

    budget: float = Field(
        ...,
        ge=0,
        description="Campaign budget"
    )

    preferred_tone: str = Field(
        default="Friendly",
        min_length=2
    )